name: Merge bot PR after CI
on: pull_request

permissions:
  contents: write
  pull-requests: write
  # checks: read # For private repositories
  # actions: read # For private repositories

jobs:
  dependabot:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.5.0
      - name: Wait other jobs
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        uses: kachick/wait-other-jobs@v3.8.1
        timeout-minutes: 10
        with:
          retry-method: 'equal_intervals'
          min-interval-seconds: '15'
          skip-same-workflow: 'true'
      - name: Approve and merge
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' || contains(steps.metadata.outputs.dependency-names, 'cachix') }}
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Avoid `automerge` renovate official feature.
  #   It wait longtime to be merged.
  # Avoid `platformAutomerge` renovate official feature.
  #   It requires many changes in GitHub settings.
  #    - `Allow auto-merge`
  #    - `Require status checks to pass before merging` and specify the status names
  #   Changing in all personal repository is annoy task for me. Even if using terrafform, getting mandatory CI names in each repo is too annoy!
  renovate:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v3.8.1
        timeout-minutes: 10
        with:
          skip-same-workflow: 'true'
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # https://github.com/kachick/anylang-template/issues/51
  selfup-runner:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'selfup-runner[bot]' }}
    steps:
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v3.8.1
        timeout-minutes: 20
        with:
          skip-same-workflow: 'true'
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --delete-branch --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
